FROM python:3.13-slim

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g $GROUP_ID appuser && \
    useradd -u $USER_ID -g $GROUP_ID -m appuser

WORKDIR /build
RUN chown -R $USER_ID:$GROUP_ID /build

COPY --chown=$USER_ID:$GROUP_ID . .

USER appuser

RUN pip install build
RUN python -m build

CMD ["sh", "-c", "cp -r dist/*.whl /output/"]
